package com.example.util

data class LocalizedStrings(
    val appTitle: String,
    val appTagline: String,
    // Navigation
    val navHome: String,
    val navPumps: String,
    val navRefills: String,
    val navCars: String,
    val navReports: String,
    val navSettings: String,
    // Home screen
    val activeVehicle: String,
    val totalVehicles: String,
    val quickRefill: String,
    val thisMonthSpend: String,
    val cngFilled: String,
    val refillVisits: String,
    val languageModuleTitle: String,
    val languageModuleDesc: String,
    val monthlySpendingTitle: String,
    val lastRefillEntry: String,
    val nearbyStations: String,
    val viewMap: String,
    val quickRefillFab: String,
    // Eco-Friendly Features
    val ecoImpactTitle: String,
    val co2Saved: String,
    val treesEquivalent: String,
    val ecoScoreTitle: String,
    val ecoScoreBadge: String,
    val ecoFuelLabel: String,
    val greenCommuter: String,
    // Station Finder & Map Search Cache
    val searchPlaceholder: String,
    val openNow: String,
    val nearby: String,
    val highestRated: String,
    val lowestPrice: String,
    val gasAvailable: String,
    val highPressure: String,
    val offlineCacheActive: String,
    val offlineCacheDesc: String,
    val cachedSearchesTitle: String,
    val offlineModeToggle: String,
    val cachedAt: String,
    val stationsFound: String,
    val navigate: String,
    val details: String,
    val cngPrice: String,
    val pressure: String,
    val rating: String,
    // Refills
    val addRefill: String,
    val odometer: String,
    val quantityKg: String,
    val pricePerKg: String,
    val totalCost: String,
    val fullTank: String,
    val notes: String,
    val saveRefill: String,
    val cancel: String,
    val selectLanguage: String,
    val close: String
)

object AppLocalization {
    fun getStrings(language: String): LocalizedStrings {
        return when {
            language.startsWith("Hindi") || language.contains("हिंदी") -> HindiStrings
            language.startsWith("Marathi") || language.contains("मराठी") -> MarathiStrings
            language.startsWith("Gujarati") || language.contains("ગુજરાતી") -> GujaratiStrings
            language.startsWith("Punjabi") || language.contains("ਪੰਜਾਬੀ") -> PunjabiStrings
            language.startsWith("Tamil") || language.contains("தமிழ்") -> TamilStrings
            language.startsWith("Telugu") || language.contains("తెలుగు") -> TeluguStrings
            language.startsWith("Bengali") || language.contains("বাংলা") -> BengaliStrings
            language.startsWith("Kannada") || language.contains("ಕನ್ನಡ") -> KannadaStrings
            language.startsWith("Spanish") || language.contains("Español") -> SpanishStrings
            else -> EnglishStrings
        }
    }

    val EnglishStrings = LocalizedStrings(
        appTitle = "CNGमित्र",
        appTagline = "Your Smart CNG Companion",
        navHome = "Home",
        navPumps = "Pumps",
        navRefills = "Refills",
        navCars = "Vehicle",
        navReports = "Expenses",
        navSettings = "Profile",
        activeVehicle = "Active Vehicle",
        totalVehicles = "vehicles",
        quickRefill = "+ Quick Refill",
        thisMonthSpend = "This Month Spend",
        cngFilled = "CNG Filled",
        refillVisits = "Refill Visits",
        languageModuleTitle = "भाषा / App Language",
        languageModuleDesc = "Select your preferred regional language for CNG station alerts, live gas pressure, and refill reports.",
        monthlySpendingTitle = "Monthly CNG Spending",
        lastRefillEntry = "Last Refill Entry",
        nearbyStations = "Nearby CNG Stations",
        viewMap = "View Map",
        quickRefillFab = "+ Quick Refill",
        ecoImpactTitle = "🌿 Eco Impact & Carbon Savings",
        co2Saved = "CO₂ Emissions Saved",
        treesEquivalent = "Trees Equivalent",
        ecoScoreTitle = "Eco-Driving Score",
        ecoScoreBadge = "Green Champion",
        ecoFuelLabel = "100% Clean Green Energy",
        greenCommuter = "Eco Commuter",
        searchPlaceholder = "Search pump, area, or road...",
        openNow = "Open Now",
        nearby = "Nearby",
        highestRated = "Highest Rated",
        lowestPrice = "Lowest Price",
        gasAvailable = "Gas Available",
        highPressure = "High Pressure (200+ bar)",
        offlineCacheActive = "⚡ Offline Map Cache Active",
        offlineCacheDesc = "View previously searched CNG locations even with no internet connection",
        cachedSearchesTitle = "Recent Cached Searches",
        offlineModeToggle = "Offline Mode",
        cachedAt = "Cached at",
        stationsFound = "Found",
        navigate = "Navigate",
        details = "Details",
        cngPrice = "CNG Price",
        pressure = "Pressure",
        rating = "Rating",
        addRefill = "Add CNG Refill",
        odometer = "Odometer Reading (km)",
        quantityKg = "Quantity (kg)",
        pricePerKg = "Price per kg (₹/kg)",
        totalCost = "Total Cost (₹)",
        fullTank = "Full Tank Filled",
        notes = "Notes / Station Comments",
        saveRefill = "Save Refill Entry",
        cancel = "Cancel",
        selectLanguage = "भाषा चुनें / Select Language",
        close = "Close"
    )

    val HindiStrings = LocalizedStrings(
        appTitle = "CNGमित्र",
        appTagline = "आपका स्मार्ट सीएनजी साथी",
        navHome = "होम",
        navPumps = "सीएनजी पंप",
        navRefills = "रिफिल",
        navCars = "वाहन",
        navReports = "खर्च",
        navSettings = "प्रोफ़ाइल",
        activeVehicle = "सक्रिय वाहन",
        totalVehicles = "वाहन",
        quickRefill = "+ त्वरित रिफिल",
        thisMonthSpend = "इस महीने का खर्च",
        cngFilled = "सीएनजी भराई",
        refillVisits = "रिफिल फेरे",
        languageModuleTitle = "भाषा / App Language",
        languageModuleDesc = "सीएनजी स्टेशन, गैस प्रेशर और रिफिल रिपोर्ट के लिए अपनी पसंदीदा भाषा चुनें।",
        monthlySpendingTitle = "मासिक सीएनजी खर्च",
        lastRefillEntry = "अंतिम रिफिल प्रविष्टि",
        nearbyStations = "निकटतम सीएनजी स्टेशन",
        viewMap = "नक्शा देखें",
        quickRefillFab = "+ त्वरित रिफिल",
        ecoImpactTitle = "🌿 पर्यावरण प्रभाव व कार्बन बचत",
        co2Saved = "बचाया गया CO₂ उत्सर्जन",
        treesEquivalent = "पेड़ों के बराबर",
        ecoScoreTitle = "इको-ड्राइविंग स्कोर",
        ecoScoreBadge = "ग्रीन चैंपियन",
        ecoFuelLabel = "100% स्वच्छ हरित ऊर्जा",
        greenCommuter = "इको चालक",
        searchPlaceholder = "पंप, क्षेत्र या मार्ग खोजें...",
        openNow = "अभी खुला है",
        nearby = "पास में",
        highestRated = "सर्वश्रेष्ठ रेटिंग",
        lowestPrice = "किफायती मूल्य",
        gasAvailable = "गैस उपलब्ध",
        highPressure = "उच्च दबाव (200+ बार)",
        offlineCacheActive = "⚡ ऑफलाइन मैप कैश सक्रिय",
        offlineCacheDesc = "बिना इंटरनेट के भी पहले खोजे गए सीएनजी स्टेशन देखें",
        cachedSearchesTitle = "हाल की कैश्ड खोजें",
        offlineModeToggle = "ऑफलाइन मोड",
        cachedAt = "कैश समय",
        stationsFound = "उपलब्ध",
        navigate = "रास्ता देखें",
        details = "विवरण",
        cngPrice = "सीएनजी दर",
        pressure = "दबाव",
        rating = "रेटिंग",
        addRefill = "सीएनजी रिफिल दर्ज करें",
        odometer = "ओडोमीटर रीडिंग (किमी)",
        quantityKg = "मात्रा (किलो)",
        pricePerKg = "मूल्य प्रति किलो (₹/किलो)",
        totalCost = "कुल खर्च (₹)",
        fullTank = "फुल टैंक भराया",
        notes = "टिप्पणी / पंप विवरण",
        saveRefill = "रिफिल सहेजें",
        cancel = "रद्द करें",
        selectLanguage = "भाषा चुनें / Select Language",
        close = "बंद करें"
    )

    val MarathiStrings = LocalizedStrings(
        appTitle = "CNGमित्र",
        appTagline = "तुमचा स्मार्ट CNG साथी",
        navHome = "मुख्यपृष्ठ",
        navPumps = "सीएनजी पंप",
        navRefills = "रिफिल",
        navCars = "वाहन",
        navReports = "खर्च",
        navSettings = "प्रोफाइल",
        activeVehicle = "सक्रिय वाहन",
        totalVehicles = "वाहने",
        quickRefill = "+ त्वरित रिफिल",
        thisMonthSpend = "या महिन्याचा खर्च",
        cngFilled = "भरलेली सीएनजी",
        refillVisits = "रिफिल फेऱ्या",
        languageModuleTitle = "भाषा / App Language",
        languageModuleDesc = "सीएनजी स्टेशन अलर्ट, गॅस प्रेशर आणि अहवालांसाठी तुमची आवडती भाषा निवडा.",
        monthlySpendingTitle = "मासिक सीएनजी खर्च",
        lastRefillEntry = "शेवटची रिफिल नोंद",
        nearbyStations = "जवळचे सीएनजी पंप",
        viewMap = "नकाशा पहा",
        quickRefillFab = "+ त्वरित रिफिल",
        ecoImpactTitle = "🌿 पर्यावरण संवर्धन व कार्बन बचत",
        co2Saved = "वाचवलेले CO₂ उत्सर्जन",
        treesEquivalent = "झाडांच्या समान",
        ecoScoreTitle = "इको-ड्रायव्हिंग स्कोअर",
        ecoScoreBadge = "ग्रीन चॅम्पियन",
        ecoFuelLabel = "100% स्वच्छ हरित ऊर्जा",
        greenCommuter = "इको प्रवासी",
        searchPlaceholder = "पंप, परिसर किंवा रस्ता शोधा...",
        openNow = "सध्या सुरू",
        nearby = "जवळचे",
        highestRated = "उत्कृष्ट रेटिंग",
        lowestPrice = "कमी दर",
        gasAvailable = "गॅस उपलब्ध",
        highPressure = "उच्च दाब (200+ बार)",
        offlineCacheActive = "⚡ ऑफलाइन नकाशा कॅश सक्रिय",
        offlineCacheDesc = "इंटरनेट नसतानाही आधी शोधलेले सीएनजी पंप सहज पहा",
        cachedSearchesTitle = "मागील कॅश शोध",
        offlineModeToggle = "ऑफलाइन मोड",
        cachedAt = "कॅश वेळ",
        stationsFound = "आढळले",
        navigate = "दिशा दाखवा",
        details = "तपशील",
        cngPrice = "सीएनजी दर",
        pressure = "दाब (Pressure)",
        rating = "रेटिंग",
        addRefill = "सीएनजी रिफिल नोंदवा",
        odometer = "ओडोमीटर रीडिंग (किमी)",
        quantityKg = "प्रमाण (किलो)",
        pricePerKg = "दर प्रति किलो (₹/किलो)",
        totalCost = "एकूण रक्कम (₹)",
        fullTank = "फुल टँक भरली",
        notes = "टीप / पंप माहिती",
        saveRefill = "रिफिल सेव्ह करा",
        cancel = "रद्द करा",
        selectLanguage = "भाषा निवडा / Select Language",
        close = "बंद करा"
    )

    val GujaratiStrings = LocalizedStrings(
        appTitle = "સીએનજીમિત્ર",
        appTagline = "પર્યાવરણમિત્ર ઇંધણ • સ્માર્ટ સીએનજી ટ્રેકિંગ",
        navHome = "હોમ",
        navPumps = "સીએનજી પંપ",
        navRefills = "રીફિલ ડાયરી",
        navCars = "વાહનો",
        navReports = "રિપોર્ટ્સ",
        navSettings = "સેટિંગ્સ",
        activeVehicle = "સક્રિય વાહન",
        totalVehicles = "વાહનો",
        quickRefill = "+ ઝડપી રીફિલ",
        thisMonthSpend = "આ મહિનાનો ખર્ચ",
        cngFilled = "પુરાવેલ સીએનજી",
        refillVisits = "રીફિલ મુલાકાતો",
        languageModuleTitle = "ભાષા / App Language",
        languageModuleDesc = "સીએનજી સ્ટેશન એલર્ટ, પ્રેશર અને રિપોર્ટ્સ માટે તમારી ભાષા પસંદ કરો.",
        monthlySpendingTitle = "માસિક સીએનજી ખર્ચ",
        lastRefillEntry = "છેલ્લી રીફિલ એન્ટ્રી",
        nearbyStations = "નજીકના સીએનજી સ્ટેશન",
        viewMap = "નકશો જુઓ",
        quickRefillFab = "+ ઝડપી રીફિલ",
        ecoImpactTitle = "🌿 પર્યાવરણ બચત અને કાર્બન ઘટાડો",
        co2Saved = "બચાવેલ CO₂ ઉત્સર્જન",
        treesEquivalent = "વૃક્ષો બરાબર",
        ecoScoreTitle = "ઇકો-ડ્રાઇવિંગ સ્કોર",
        ecoScoreBadge = "ગ્રીન ચેમ્પિયન",
        ecoFuelLabel = "100% શુદ્ધ ગ્રીન એનર્જી",
        greenCommuter = "ઇકો ડ્રાઇવર",
        searchPlaceholder = "પંપ, વિસ્તાર કે રોડ શોધો...",
        openNow = "હાલ ખુલ્લું",
        nearby = "નજીક",
        highestRated = "શ્રેષ્ઠ રેટિંગ",
        lowestPrice = "ઓછો ભાવ",
        gasAvailable = "ગેસ ઉપલબ્ધ",
        highPressure = "હાઇ પ્રેશર (200+ બાર)",
        offlineCacheActive = "⚡ ઓફલાઇન મેપ કેશ સક્રિય",
        offlineCacheDesc = "ઇન્ટરનેટ વિના પણ અગાઉ શોધેલા સીએનજી પંપ જુઓ",
        cachedSearchesTitle = "તાજેતરના કેશ્ડ સર્ચ",
        offlineModeToggle = "ઓફલાઇન મોડ",
        cachedAt = "કેશ સમય",
        stationsFound = "મળ્યા",
        navigate = "નેવિગેટ",
        details = "વિગતો",
        cngPrice = "સીએનજી ભાવ",
        pressure = "પ્રેશર",
        rating = "રેટિંગ",
        addRefill = "સીએનજી રીફિલ નોંધો",
        odometer = "ઓડોમીટર રીડિંગ (કિમી)",
        quantityKg = "જથ્થો (કિલો)",
        pricePerKg = "ભાવ પ્રતિ કિલો (₹/કિલો)",
        totalCost = "કુલ ખર્ચ (₹)",
        fullTank = "ફુલ ટેન્ક",
        notes = "નોંધ",
        saveRefill = "સાચવો",
        cancel = "રદ કરો",
        selectLanguage = "ભાષા પસંદ કરો / Select Language",
        close = "બંધ કરો"
    )

    val PunjabiStrings = LocalizedStrings(
        appTitle = "ਸੀਐਨਜੀ ਮਿੱਤਰ",
        appTagline = "ਹਰਾ ਬਾਲਣ • ਸਮਾਰਟ ਸੀਐਨਜੀ ਟਰੈਕਿੰਗ",
        navHome = "ਮੁੱਖ ਪੰਨਾ",
        navPumps = "ਸੀਐਨਜੀ ਪੰਪ",
        navRefills = "ਰਿਫਿਲ ਡਾਇਰੀ",
        navCars = "ਗੱਡੀਆਂ",
        navReports = "ਰਿਪੋਰਟਾਂ",
        navSettings = "ਸੈਟਿੰਗਾਂ",
        activeVehicle = "ਮੌਜੂਦਾ ਗੱਡੀ",
        totalVehicles = "ਗੱਡੀਆਂ",
        quickRefill = "+ ਤੇਜ਼ ਰਿਫਿਲ",
        thisMonthSpend = "ਇਸ ਮਹੀਨੇ ਦਾ ਖਰਚਾ",
        cngFilled = "ਭਰੀ ਹੋਈ ਸੀਐਨਜੀ",
        refillVisits = "ਰਿਫਿਲ ਫੇਰੇ",
        languageModuleTitle = "ਭਾਸ਼ਾ / App Language",
        languageModuleDesc = "ਸੀਐਨਜੀ ਪੰਪ, ਗੈਸ ਪ੍ਰੈਸ਼ਰ ਅਤੇ ਰਿਪੋਰਟਾਂ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ।",
        monthlySpendingTitle = "ਮਹੀਨਾਵਾਰ ਸੀਐਨਜੀ ਖਰਚਾ",
        lastRefillEntry = "ਆਖਰੀ ਰਿਫਿਲ ਇੰਦਰਾਜ",
        nearbyStations = "ਨੇੜਲੇ ਸੀਐਨਜੀ ਸਟੇਸ਼ਨ",
        viewMap = "ਨਕਸ਼ਾ ਦੇਖੋ",
        quickRefillFab = "+ ਤੇਜ਼ ਰਿਫਿਲ",
        ecoImpactTitle = "🌿 ਵਾਤਾਵਰਣ ਬਚਤ ਤੇ ਕਾਰਬਨ ਘਟਾਓ",
        co2Saved = "ਬਚਾਈ ਗਈ CO₂ ਨਿਕਾਸੀ",
        treesEquivalent = "ਰੁੱਖਾਂ ਦੇ ਬਰਾਬਰ",
        ecoScoreTitle = "ਈਕੋ-ਡਰਾਈਵਿੰਗ ਸਕੋਰ",
        ecoScoreBadge = "ਗਰੀਨ ਚੈਂਪੀਅਨ",
        ecoFuelLabel = "100% ਸਾਫ਼ ਹਰੀ ਊਰਜਾ",
        greenCommuter = "ਈਕੋ ਡਰਾਈਵਰ",
        searchPlaceholder = "ਪੰਪ, ਇਲਾਕਾ ਜਾਂ ਰੋਡ ਖੋਜੋ...",
        openNow = "ਹੁਣੇ ਖੁੱਲ੍ਹਾ",
        nearby = "ਨੇੜੇ",
        highestRated = "ਸਭ ਤੋਂ ਵਧੀਆ ਰੇਟਿੰਗ",
        lowestPrice = "ਘੱਟ ਕੀਮਤ",
        gasAvailable = "ਗੈਸ ਉਪਲਬਧ",
        highPressure = "ਵੱਧ ਪ੍ਰੈਸ਼ਰ (200+ ਬਾਰ)",
        offlineCacheActive = "⚡ ਔਫਲਾਈਨ ਨਕਸ਼ਾ ਕੈਸ਼ ਚਾਲੂ",
        offlineCacheDesc = "ਬਿਨਾਂ ਇੰਟਰਨੈਟ ਤੋਂ ਵੀ ਪਹਿਲਾਂ ਖੋਜੇ ਸੀਐਨਜੀ ਪੰਪ ਦੇਖੋ",
        cachedSearchesTitle = "ਹਾਲੀਆ ਕੈਸ਼ ਖੋਜਾਂ",
        offlineModeToggle = "ਔਫਲਾਈਨ ਮੋਡ",
        cachedAt = "ਕੈਸ਼ ਸਮਾਂ",
        stationsFound = "ਮਿਲੇ",
        navigate = "ਰਸਤਾ ਦੇਖੋ",
        details = "ਵੇਰਵੇ",
        cngPrice = "ਸੀਐਨਜੀ ਕੀਮਤ",
        pressure = "ਪ੍ਰੈਸ਼ਰ",
        rating = "ਰੇਟਿੰਗ",
        addRefill = "ਸੀਐਨਜੀ ਰਿਫਿਲ ਦਰਜ ਕਰੋ",
        odometer = "ਓਡੋਮੀਟਰ ਰੀਡਿੰਗ (ਕਿਮੀ)",
        quantityKg = "ਮਾਤਰਾ (ਕਿਲੋ)",
        pricePerKg = "ਕੀਮਤ ਪ੍ਰਤੀ ਕਿਲੋ (₹/ਕਿਲੋ)",
        totalCost = "ਕੁੱਲ ਖਰਚਾ (₹)",
        fullTank = "ਫੁੱਲ ਟੈਂਕ",
        notes = "ਨੋਟ",
        saveRefill = "ਸੰਭਾਲੋ",
        cancel = "ਰੱਦ ਕਰੋ",
        selectLanguage = "ਭਾਸ਼ਾ ਚੁਣੋ / Select Language",
        close = "ਬੰਦ ਕਰੋ"
    )

    val TamilStrings = LocalizedStrings(
        appTitle = "சிஎன்ஜி மித்ரா",
        appTagline = "பசுமை எரிபொருள் • ஸ்மார்ட் சிஎன்ஜி கண்காணிப்பு",
        navHome = "முகப்பு",
        navPumps = "சிஎன்ஜி பங்க்",
        navRefills = "நிரப்பல் டைரி",
        navCars = "வாகனங்கள்",
        navReports = "அறிக்கைகள்",
        navSettings = "அமைப்புகள்",
        activeVehicle = "செயலில் உள்ள வாகனம்",
        totalVehicles = "வாகனங்கள்",
        quickRefill = "+ விரைவு நிரப்பல்",
        thisMonthSpend = "இந்த மாத செலவு",
        cngFilled = "நிரப்பப்பட்ட சிஎன்ஜி",
        refillVisits = "நிரப்பல் வருகைகள்",
        languageModuleTitle = "மொழி / App Language",
        languageModuleDesc = "சிஎன்ஜி நிலையம், பிரஷர் மற்றும் அறிக்கைகளுக்கான மொழியைத் தேர்வுசெய்யவும்.",
        monthlySpendingTitle = "மாதாந்திர சிஎன்ஜி செலவு",
        lastRefillEntry = "கடைசி நிரப்பல் பதிவு",
        nearbyStations = "அருகிலுள்ள சிஎன்ஜி நிலையங்கள்",
        viewMap = "வரைபடம் பார்க்க",
        quickRefillFab = "+ விரைவு நிரப்பல்",
        ecoImpactTitle = "🌿 சுற்றுச்சூழல் பாதுகாப்பு & கார்பன் சேமிப்பு",
        co2Saved = "சேமிக்கப்பட்ட CO₂ உமிழ்வு",
        treesEquivalent = "மரங்களுக்குச் சமம்",
        ecoScoreTitle = "சுற்றுச்சூழல் ஓட்டுநர் மதிப்பெண்",
        ecoScoreBadge = "பசுமை சாம்பியன்",
        ecoFuelLabel = "100% தூய பசுமை ஆற்றல்",
        greenCommuter = "சுற்றுச்சூழல் பயணி",
        searchPlaceholder = "பங்க், பகுதி அல்லது சாலையைத் தேடுங்கள்...",
        openNow = "தற்போது திறந்துள்ளது",
        nearby = "அருகில்",
        highestRated = "சிறந்த மதிப்பீடு",
        lowestPrice = "குறைந்த விலை",
        gasAvailable = "எரிவாயு உள்ளது",
        highPressure = "அதிவேக பிரஷர் (200+ பார்)",
        offlineCacheActive = "⚡ ஆஃப்லைன் வரைபட கேச் இயங்குகிறது",
        offlineCacheDesc = "இணையம் இல்லாமலும் முன்னர் தேடிய சிஎன்ஜி நிலையங்களைப் பார்க்கலாம்",
        cachedSearchesTitle = "சமீபத்திய கேச் தேடல்கள்",
        offlineModeToggle = "ஆஃப்லைன் முறை",
        cachedAt = "சேமிக்கப்பட்ட நேரம்",
        stationsFound = "கிடைத்தது",
        navigate = "வழிசெலுத்து",
        details = "விவரங்கள்",
        cngPrice = "சிஎன்ஜி விலை",
        pressure = "பிரஷர்",
        rating = "மதிப்பீடு",
        addRefill = "சிஎன்ஜி நிரப்பலைச் சேர்க்கவும்",
        odometer = "ஓடோமீட்டர் அளவு (கிமீ)",
        quantityKg = "அளவு (கிலோ)",
        pricePerKg = "கிலோ விலை (₹/கிலோ)",
        totalCost = "மொத்த செலவு (₹)",
        fullTank = "முழு டேங்க்",
        notes = "குறிப்பு",
        saveRefill = "சேமிக்கவும்",
        cancel = "ரத்துசெய்",
        selectLanguage = "மொழியைத் தேர்வுசெய்யவும் / Select Language",
        close = "மூடு"
    )

    val TeluguStrings = LocalizedStrings(
        appTitle = "సీఎన్‌జీ మిత్ర",
        appTagline = "హరిత ఇంధనం • స్మార్ట్ సీఎన్‌జీ ట్రాకింగ్",
        navHome = "హోమ్",
        navPumps = "సీఎన్‌జీ పంపులు",
        navRefills = "రీఫిల్ డైరీ",
        navCars = "వాహనాలు",
        navReports = "నివేదికలు",
        navSettings = "సెట్టింగ్‌లు",
        activeVehicle = "ప్రస్తుత వాహనం",
        totalVehicles = "వాహనాలు",
        quickRefill = "+ త్వరిత రీఫిల్",
        thisMonthSpend = "ఈ నెల ఖర్చు",
        cngFilled = "నింపిన సీఎన్‌జీ",
        refillVisits = "రీఫిల్ సందర్శనలు",
        languageModuleTitle = "భాష / App Language",
        languageModuleDesc = "సీఎన్‌జీ స్టేషన్లు, గ్యాస్ ప్రెజర్ మరియు నివేదికల కోసం మీ భాషను ఎంచుకోండి.",
        monthlySpendingTitle = "నెలవారీ సీఎన్‌జీ ఖర్చు",
        lastRefillEntry = "చివరి రీఫిల్ నమోదు",
        nearbyStations = "సమీప సీఎన్‌జీ స్టేషన్లు",
        viewMap = "మ్యాప్ చూడండి",
        quickRefillFab = "+ త్వరిత రీఫిల్",
        ecoImpactTitle = "🌿 పర్యావరణ పరిరక్షణ & కార్బన్ ఆదా",
        co2Saved = "ఆదా చేసిన CO₂ ఉద్గారాలు",
        treesEquivalent = "చెట్లతో సమానం",
        ecoScoreTitle = "ఎకో-డ్రైవింగ్ స్కోరు",
        ecoScoreBadge = "గ్రీన్ ఛాంపియన్",
        ecoFuelLabel = "100% స్వచ్ఛమైన హరిత శక్తి",
        greenCommuter = "ఎకో ప్రయాణీకుడు",
        searchPlaceholder = "పంపు, ప్రాంతం లేదా రోడ్డును వెతకండి...",
        openNow = "ఇప్పుడు తెరిచి ఉంది",
        nearby = "సమీపంలో",
        highestRated = "అత్యుత్తమ రేటింగ్",
        lowestPrice = "తక్కువ ధర",
        gasAvailable = "గ్యాస్ అందుబాటులో ఉంది",
        highPressure = "అధిక ప్రెజర్ (200+ బార్)",
        offlineCacheActive = "⚡ ఆఫ్‌లైన్ మ్యాప్ కాష్ యాక్టివ్",
        offlineCacheDesc = "ఇంటర్నెట్ లేనప్పుడు కూడా మునుపు శోధించిన సీఎన్‌జీ పంపులను చూడండి",
        cachedSearchesTitle = "ఇటీవలి కాష్ శోధనలు",
        offlineModeToggle = "ఆఫ్‌లైన్ మోడ్",
        cachedAt = "కాష్ చేసిన సమయం",
        stationsFound = "లభించాయి",
        navigate = "మార్గం",
        details = "వివరాలు",
        cngPrice = "సీఎన్‌జీ ధర",
        pressure = "ప్రెజర్",
        rating = "రేటింగ్",
        addRefill = "సీఎన్‌జీ రీఫిల్ నమోదు",
        odometer = "ఓడోమీటర్ రీడింగ్ (కిమీ)",
        quantityKg = "పరిమాణం (కిలో)",
        pricePerKg = "కిలో ధర (₹/కిలో)",
        totalCost = "మొత్తం ఖర్చు (₹)",
        fullTank = "ఫుల్ ట్యాంక్",
        notes = "గమనిక",
        saveRefill = "సేవ్ చేయండి",
        cancel = "రద్దు",
        selectLanguage = "భాషను ఎంచుకోండి / Select Language",
        close = "మూసివేయి"
    )

    val BengaliStrings = LocalizedStrings(
        appTitle = "সিএনজি মিত্র",
        appTagline = "পরিবেশবান্ধব জ্বালানি • স্মার্ট সিএনজি ট্র্যাকিং",
        navHome = "হোম",
        navPumps = "সিএনজি পাম্প",
        navRefills = "রিফিল ডায়েরি",
        navCars = "যানবাহন",
        navReports = "রিপোর্ট",
        navSettings = "সেটিংস",
        activeVehicle = "সক্রিয় গাড়ি",
        totalVehicles = "গাড়ি",
        quickRefill = "+ দ্রুত রিফিল",
        thisMonthSpend = "এই মাসের খরচ",
        cngFilled = "ভরা সিএনজি",
        refillVisits = "রিফিল সংখ্যা",
        languageModuleTitle = "ভাষা / App Language",
        languageModuleDesc = "সিএনজি স্টেশন, গ্যাস প্রেসার এবং রিপোর্টের জন্য আপনার পছন্দের ভাষা নির্বাচন করুন।",
        monthlySpendingTitle = "মাসিক সিএনজি খরচ",
        lastRefillEntry = "সর্বশেষ রিফিল এন্ট্রি",
        nearbyStations = "কাছাকাছি সিএনজি স্টেশন",
        viewMap = "ম্যাপ দেখুন",
        quickRefillFab = "+ দ্রুত রিফিল",
        ecoImpactTitle = "🌿 পরিবেশ সংরক্ষণ ও কার্বন সাশ্রয়",
        co2Saved = "সংরক্ষিত CO₂ নির্গমন",
        treesEquivalent = "গাছের সমতুল্য",
        ecoScoreTitle = "ইকো-ড্রাইভিং স্কোর",
        ecoScoreBadge = "গ্রিন চ্যাম্পিয়ন",
        ecoFuelLabel = "১০০% বিশুদ্ধ সবুজ শক্তি",
        greenCommuter = "ইকো চালক",
        searchPlaceholder = "পাম্প, এলাকা বা রাস্তা খুঁজুন...",
        openNow = "এখন খোলা",
        nearby = "কাছে",
        highestRated = "সেরা রেটিং",
        lowestPrice = "কম দাম",
        gasAvailable = "গ্যাস উপলব্ধ",
        highPressure = "উচ্চ চাপ (২০০+ বার)",
        offlineCacheActive = "⚡ অফলাইন ম্যাপ ক্যাশ সক্রিয়",
        offlineCacheDesc = "ইন্টারনেট ছাড়াও আগে খোঁজা সিএনজি পাম্প দেখুন",
        cachedSearchesTitle = "সাম্প্রতিক ক্যাশ অনুসন্ধান",
        offlineModeToggle = "অফলাইন মোড",
        cachedAt = "ক্যাশ সময়",
        stationsFound = "পাওয়া গেছে",
        navigate = "পথনির্দেশ",
        details = "বিস্তারিত",
        cngPrice = "সিএনজি দর",
        pressure = "চাপ",
        rating = "রেটিং",
        addRefill = "সিএনজি রিফিল যোগ করুন",
        odometer = "ওডোমিটার রিডিং (কিমি)",
        quantityKg = "পরিমাণ (কেজি)",
        pricePerKg = "দর প্রতি কেজি (₹/কেজি)",
        totalCost = "মোট খরচ (₹)",
        fullTank = "ফুল ট্যাঙ্ক",
        notes = "মন্তব্য",
        saveRefill = "সংরক্ষণ করুন",
        cancel = "বাতিল",
        selectLanguage = "ভাষা নির্বাচন করুন / Select Language",
        close = "বন্ধ করুন"
    )

    val KannadaStrings = LocalizedStrings(
        appTitle = "ಸಿಎನ್‌ಜಿ ಮಿತ್ರ",
        appTagline = "ಹಸಿರು ಇಂಧನ • ಸ್ಮಾರ್ಟ್ ಸಿಎನ್‌ಜಿ ಟ್ರ್ಯಾಕಿಂಗ್",
        navHome = "ಮುಖಪುಟ",
        navPumps = "ಸಿಎನ್‌ಜಿ ಪಂಪ್",
        navRefills = "ರೀಫಿಲ್ ಡೈರಿ",
        navCars = "ವಾಹನಗಳು",
        navReports = "ವರದಿಗಳು",
        navSettings = "ಸೆಟ್ಟಿಂಗ್ಸ್",
        activeVehicle = "ಸಕ್ರಿಯ ವಾಹನ",
        totalVehicles = "ವಾಹನಗಳು",
        quickRefill = "+ ತ್ವರಿತ ರೀಫಿಲ್",
        thisMonthSpend = "ಈ ತಿಂಗಳ ಖರ್ಚು",
        cngFilled = "ತುಂಬಿದ ಸಿಎನ್‌ಜಿ",
        refillVisits = "ರೀಫಿಲ್ ಭೇಟಿಗಳು",
        languageModuleTitle = "ಭಾಷೆ / App Language",
        languageModuleDesc = "ಸಿಎನ್‌ಜಿ ಪಂಪ್, ಪ್ರೆಶರ್ ಮತ್ತು ವರದಿಗಳಿಗಾಗಿ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
        monthlySpendingTitle = "ಮಾಸಿಕ ಸಿಎನ್‌ಜಿ ವೆಚ್ಚ",
        lastRefillEntry = "ಕೊನೆಯ ರೀಫಿಲ್ ವಿವರ",
        nearbyStations = "ಹತ್ತಿರದ ಸಿಎನ್‌ಜಿ ಕೇಂದ್ರಗಳು",
        viewMap = "ನಕ್ಷೆ ನೋಡಿ",
        quickRefillFab = "+ ತ್ವರಿತ ರೀಫಿಲ್",
        ecoImpactTitle = "🌿 ಪರಿಸರ ಉಳಿತಾಯ ಮತ್ತು ಇಂಗಾಲ ಕಡಿತ",
        co2Saved = "ಉಳಿಸಿದ CO₂ ಹೊರಸೂಸುವಿಕೆ",
        treesEquivalent = "ಮರಗಳಿಗೆ ಸಮಾನ",
        ecoScoreTitle = "ಇಕೋ-ಡ್ರೈವಿಂಗ್ ಸ್ಕೋರ್",
        ecoScoreBadge = "ಗ್ರೀನ್ ಚಾಂಪಿಯನ್",
        ecoFuelLabel = "100% ಶುದ್ಧ ಹಸಿರು ಶಕ್ತಿ",
        greenCommuter = "ಇಕೋ ಚಾಲಕ",
        searchPlaceholder = "ಪಂಪ್, ಪ್ರದೇಶ ಅಥವಾ ರಸ್ತೆ ಹುಡುಕಿ...",
        openNow = "ಈಗ ತೆರೆದಿದೆ",
        nearby = "ಹತ್ತಿರದ",
        highestRated = "ಉತ್ತಮ ರೇಟಿಂಗ್",
        lowestPrice = "ಕಡಿಮೆ ಬೆಲೆ",
        gasAvailable = "ಗ್ಯಾಸ್ ಲಭ್ಯವಿದೆ",
        highPressure = "ಹೆಚ್ಚಿನ ಒತ್ತಡ (200+ ಬಾರ್)",
        offlineCacheActive = "⚡ ಆಫ್‌ಲೈನ್ ನಕ್ಷೆ ಕ್ಯಾಶ್ ಸಕ್ರಿಯವಾಗಿದೆ",
        offlineCacheDesc = "ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದಿದ್ದರೂ ಹಿಂದೆ ಹುಡುಕಿದ ಸಿಎನ್‌ಜಿ ಕೇಂದ್ರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
        cachedSearchesTitle = "ಇತ್ತೀಚಿನ ಕ್ಯಾಶ್ ಹುಡುಕಾಟಗಳು",
        offlineModeToggle = "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
        cachedAt = "ಕ್ಯಾಶ್ ಸಮಯ",
        stationsFound = "ಕಂಡುಬಂದಿವೆ",
        navigate = "ಮಾರ್ಗ",
        details = "ವಿವರಗಳು",
        cngPrice = "ಸಿಎನ್‌ಜಿ ಬೆಲೆ",
        pressure = "ಒತ್ತಡ",
        rating = "ರೇಟಿಂಗ್",
        addRefill = "ಸಿಎನ್‌ಜಿ ರೀಫಿಲ್ ಸೇರಿಸಿ",
        odometer = "ಓಡೋಮೀಟರ್ ರೀಡಿಂಗ್ (ಕಿಮೀ)",
        quantityKg = "ಪ್ರಮಾಣ (ಕೆಜಿ)",
        pricePerKg = "ಬೆಲೆ ಪ್ರತಿ ಕೆಜಿ (₹/ಕೆಜಿ)",
        totalCost = "ಒಟ್ಟು ವೆಚ್ಚ (₹)",
        fullTank = "ಫುಲ್ ಟ್ಯಾಂಕ್",
        notes = "ಟಿಪ್ಪಣಿ",
        saveRefill = "ಉಳಿಸಿ",
        cancel = "ರದ್ದುಮಾಡಿ",
        selectLanguage = "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ / Select Language",
        close = "ಮುಚ್ಚಿ"
    )

    val SpanishStrings = LocalizedStrings(
        appTitle = "CNG Amigo",
        appTagline = "Combustible Ecológico • Rastreo Inteligente GNC",
        navHome = "Inicio",
        navPumps = "Estaciones",
        navRefills = "Recargas",
        navCars = "Vehículos",
        navReports = "Reportes",
        navSettings = "Ajustes",
        activeVehicle = "Vehículo Activo",
        totalVehicles = "vehículos",
        quickRefill = "+ Recarga Rápida",
        thisMonthSpend = "Gasto del Mes",
        cngFilled = "GNC Cargado",
        refillVisits = "Visitas de Carga",
        languageModuleTitle = "Idioma / Language",
        languageModuleDesc = "Selecciona tu idioma para alertas de estaciones, presión de gas y reportes.",
        monthlySpendingTitle = "Gasto Mensual de GNC",
        lastRefillEntry = "Última Recarga",
        nearbyStations = "Estaciones Cercanas",
        viewMap = "Ver Mapa",
        quickRefillFab = "+ Recarga Rápida",
        ecoImpactTitle = "🌿 Impacto Ecológico y Ahorro de Carbono",
        co2Saved = "Emisiones de CO₂ Ahorradas",
        treesEquivalent = "Árboles Equivalentes",
        ecoScoreTitle = "Puntaje de Conducción Eco",
        ecoScoreBadge = "Campeón Verde",
        ecoFuelLabel = "100% Energía Limpia y Verde",
        greenCommuter = "Conductor Ecológico",
        searchPlaceholder = "Buscar estación, zona o calle...",
        openNow = "Abierto Ahora",
        nearby = "Cercano",
        highestRated = "Mejor Calificado",
        lowestPrice = "Menor Precio",
        gasAvailable = "Gas Disponible",
        highPressure = "Alta Presión (200+ bar)",
        offlineCacheActive = "⚡ Caché de Mapa Sin Conexión Activo",
        offlineCacheDesc = "Consulta estaciones de GNC buscadas anteriormente incluso sin internet",
        cachedSearchesTitle = "Búsquedas en Caché Recientes",
        offlineModeToggle = "Modo Sin Conexión",
        cachedAt = "Guardado a las",
        stationsFound = "Encontradas",
        navigate = "Navegar",
        details = "Detalles",
        cngPrice = "Precio GNC",
        pressure = "Presión",
        rating = "Calificación",
        addRefill = "Registrar Recarga",
        odometer = "Lectura Odómetro (km)",
        quantityKg = "Cantidad (kg)",
        pricePerKg = "Precio por kg (₹/kg)",
        totalCost = "Costo Total (₹)",
        fullTank = "Tanque Lleno",
        notes = "Notas / Comentarios",
        saveRefill = "Guardar Recarga",
        cancel = "Cancelar",
        selectLanguage = "Seleccionar Idioma",
        close = "Cerrar"
    )
}
